<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<?php
    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
    $currentStore = $storeManager->getStore();
    $baseUrl = $currentStore->getBaseUrl();
    $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<div class="product-addto-links" data-role="add-to-links">
	<a href="#" class="action sipping-option-link">
		<img src="<?= $mediaUrl."images/icon/box-detail.png"; ?>" alt="">
		<span>Sipping Option</span>
	</a>
    <?php echo $block->getChildHtml(); ?>
</div>
