<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Wishlist\Block\Link */
?>
<li class="lane-top">|</li>
<li class="link wishlist" data-bind="scope: 'wishlist'">
    <a <?php /* @escapeNotVerified */ echo $block->getLinkAttributes() ?>>My Wishlist
        <!-- ko if: wishlist().counter -->
        <span data-bind="text: wishlist().counter" class="counter qty"></span>
        <!-- /ko -->
    </a>
</li>
<li class="lane-top">|</li>
<li class="lane-top">Manufacturers</li>
<li class="lane-top">|</li>
<li class="lane-top">Checkout</li>
<li class="lane-top">|</li>
<li class="lane-top">Teletron Ads</li>
<li class="lane-top">|</li>
<li class="lane-top">Store Locator</li>
<li class="lane-top">|</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
