<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Wishlist\Block\Link */
?>
<?php
    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
    $currentStore = $storeManager->getStore();
    $baseUrl = $currentStore->getBaseUrl();
?>
<li class="lane-top">|</li>
<li class="link wishlist" data-bind="scope: 'wishlist'">
    <a <?php /* @escapeNotVerified */ echo $block->getLinkAttributes() ?>>My Wishlist
        <!-- ko if: wishlist().counter -->
        <span data-bind="text: wishlist().counter" class="counter qty"></span>
        <!-- /ko -->
    </a>
</li>
<li class="lane-top">|</li>
<li class="lane-top"><a href="<?= $baseUrl ?>brand" title="">Manufacturers</a></li>
<li class="lane-top">|</li>
<li class="lane-top"><a href="#" title="">Checkout</a></li>
<li class="lane-top">|</li>
<li class="lane-top"><a href="#" title="">Teletron Ads</a></li>
<li class="lane-top">|</li>
<li class="lane-top"><a href="#" title="">Store Locator</a></li>
<li class="lane-top">|</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
